
// Quartus Prime Verilog Template
// Simple Dual Port RAM with separate read/write addresses and
// separate read/write clocks
module simple_dual_port_ram_dual_clock
#(parameter DATA_WIDTH=8, parameter ADDR_WIDTH=13)
(
	input [(DATA_WIDTH-1):0] data,
	input [(ADDR_WIDTH-1):0] read_addr, write_addr,
	input we, read_clock, write_clock,
	output reg [(DATA_WIDTH-1):0] q
);

	// Declare the RAM variable
	reg [DATA_WIDTH-1:0] ram[2**ADDR_WIDTH-1:0];

	always @ (posedge write_clock)
	begin
		// Write
		if (we)
			ram[write_addr] <= data;
	end

	always @ (posedge read_clock)
	begin
		// Read
		q <= ram[read_addr];
	end

endmodule



//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module MOS6502(

	//////////// CLOCK //////////
	input 		          		CLOCK0_50,
	input 		          		CLOCK1_50,
	input 		          		CLOCK2_50,

	//////////// KEY //////////
	input 		          		CPU_RESET_n,
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// HDMI Out //////////
	output		          		HDMI_I2S,
	output		          		HDMI_LRCLK,
	output		          		HDMI_MCLK,
	output		          		HDMI_SCLK,
	output		          		HDMI_TX_CLK,
	output		          		HDMI_TX_DE,
	output		    [23:0]		HDMI_TX_D,
	output		          		HDMI_TX_HS,
	input 		          		HDMI_TX_INT,
	output		          		HDMI_TX_VS,

	///////// I2C for Camera, Audio and Video-In /////////
	output             FPGA_I2C_SCLK,
	inout              FPGA_I2C_SDAT
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire rst_n;

wire [7:0]read_memory_data;


wire [15:0]mem_addr;
wire mem_write;
wire [7:0]mem_bus; // valid when mem_write is true.


wire [7:0]vga_bus_data;
wire [12:0]vga_buffer_query;
wire [12:0]vga_write_addr;
wire [7:0]vga_buffer_output;
wire [7:0]vga_data_write;
wire vga_write_enable;


wire ninit_done;

//=======================================================
//  Structural coding
//=======================================================

assign rst_n = !ninit_done & CPU_RESET_n;


agilex_5_reset_release reset_release_Inst (
	.ninit_done(ninit_done));


hdmi_clock_pll HdmiPll(
	.refclk(CLOCK2_50),
	.locked(),
	.rst(~rst_n),
	.outclk_0(HDMI_TX_CLK));


assign LEDR = mem_addr[9:0];
topEntity mos6502(
	.CLK(CLOCK2_50),
	.RESET(~rst_n),
	.ENABLE(1),
	
	// Inputs
	.MEM_DATA_IN(read_memory_data),

	// Outputs
	.MEM_ADDR(mem_addr),
	.MEM_W(mem_write),
	.MEM_W_DATA(mem_bus));


simple_dual_port_ram_dual_clock display_buffer(
	.data(vga_data_write),
	.read_addr(vga_buffer_query),
	.write_addr(vga_write_addr),
	.we(vga_write_enable),
	.read_clock(HDMI_TX_CLK),
	.write_clock(CLOCK2_50),
	.q(vga_bus_data));


memoryController mem_ctr(
	.CLK(CLOCK2_50),
	.RESET(~rst_n),
	.ENABLE(1),
	
	// Inputs
   .ADDR_QUERY(mem_addr),
   .CPU_DATA_OUT(mem_bus),
   .CPU_DATA_W(mem_write),

   // Outputs
   .CPU_DATA_IN(read_memory_data),
   .VGA_ADDR(vga_write_addr),
   .VGA_DATA_OUT(vga_data_write),
   .VGA_DATA_W(vga_write_enable));


// Display Driver

I2C_HDMI_Config u_I2C_HDMI_Config (
	.iCLK(CLOCK2_50),
	.iRST_N(rst_n),
	.I2C_SCLK(FPGA_I2C_SCLK),
	.I2C_SDAT(FPGA_I2C_SDAT),
	.HDMI_TX_INT(HDMI_TX_INT));


wire clash_hs;
wire clash_vs;

wire [7:0] vga_data_direct = vga_bus_data | 3;

vgaDriver vga_driver(
	.CLK(HDMI_TX_CLK),
	.RESET(~rst_n),
	.ENABLE(1),
	.BUFFER_DATA(vga_data_direct),
	.BUFFER_QUERY(vga_buffer_query),
	.VGA_DATA(HDMI_TX_D),
	.VGA_ACTIVE(HDMI_TX_DE),
	.VGA_H_SYNC(clash_hs),
	.VGA_V_SYNC(clash_vs));

assign HDMI_TX_HS = ~clash_hs;
assign HDMI_TX_VS = ~clash_vs;

endmodule
